lib/rack/cache/context.rb, test/context_test.rb
When making a CORS (http://www.w3.org/TR/cors/) request, first a preflight OPTIONS request is sent to ensure the request is valid. Once receiving a response from the OPTIONS request the real request is then made (so long as the OPTIONS response confirmed its validity) e.g.
some-origin sends => OPTIONS /foo/bar to some-other-origin
some-origin is allowed access to some-other-origin
some-origin sends => GET /foo/bar to some-other-origin
Currently the OPTIONS request is invalidating the /foo/bar cache and is rendering the cache useless for cross origin requests, such as using an AngularJS front end with a Sinatra JSON API.
I've put together a simple solution which checks for OPTIONS requests before invalidating the cache. The OPTIONS response isn't cached and is always passed.
=> Not invalidating the cache for preflight CORS request

lib/rack/cache/metastore.rb
This corrects the constant name for the NotImplementedError exception raised when these abstract method implementations are called. A small change but will impact the readability of test failures when stores do not override abstract method implementations.
=> Correct NotImplementedError exception constant

lib/rack/cache/response.rb, test/response_test.rb
We encountered a site which had an Expires header which was unparseable by `Time.httpdate`. This caused `Time.httpdate` to raise [`ArgumentError: not RFC 2616 compliant date`](https://github.com/ruby/ruby/blob/v2_0_0_481/lib/time.rb#L509).
This PR makes `expires` return `nil` if the Expires header is not parseable.
=> Return nil for expires if the Expires header is not parseable.

lib/rack/cache/context.rb, test/context_test.rb
This is the same patch as https://github.com/rtomayko/rack-cache/pull/69 - I'm reopening it, because when you don't set rack.methodoverride.original_method after overriding the request method, there's no way to know what the original request was.
=> After overriding the REQUEST_METHOD, store the original request method in "rack.methodoverride.original_method"

lib/rack/cache/context.rb
I lack the historical context for the original rescue clauses (dating back to 2009) and don't know if there was a store implementation that would raise an exception that didn't descend from StandardError.  But swallowing all exceptions can lead to some unexpected behavior, especially in a multi-threaded environment.
=> Rescue StandardError instead of Exception so things like interrupts continue to work.

lib/rack/cache/key.rb, test/key_test.rb
Query string keys must be escaped after the split bacause:
- Query string could look like 'weird%3Dkey=whatever'
- Rake util's unescape method forces utf-8 encoding on strings, which will cause the "invalid byte sequence in UTF-8" error for the most string methods called on badly encoded strings, e.g. Rack::Utils::unescape('%D0%BA=%D1').split('=')
=> Fix key generation

README.md, lib/rack/cache/entitystore.rb, lib/rack/cache/metastore.rb, lib/rack/cache/storage.rb, test/entitystore_test.rb
This PR adds the ability to set rack-cache entity store to nil, e.g.:
```
require 'rack/cache'
use Rack::Cache,
:metastore   => 'file:/var/cache/rack/meta',
:entitystore => nil,
:verbose     => true
run app
```
or
```
require 'rack/cache'
use Rack::Cache,
:metastore   => 'file:/var/cache/rack/meta',
:entitystore => 'dummy:',
:verbose     => true
run app
```
Both values (nil or 'dummy:') in the entitystore option enable the Dummy backend.
When the Dummy backend is used for the entity store, rack-cache doesn't persist response bodies. If a cached response is still fresh, or if it's stale but found to be still valid, rack-cache returns only the response headers with an empty body. The code performing the request should check if the response comes from the cache (e.g. checking the …
=> Added a new Dummy backend for Entity Store

README.md, lib/rack/cache/entity_store.rb, lib/rack/cache/meta_store.rb, test/meta_store_test.rb
streamed bodies can only be read once, so we cannot read them and then return them
hotfix for 1.6.0 release ... need a bit more time and a minor release to implement a proper fix
reverts https://github.com/rtomayko/rack-cache/pull/133
fixes https://github.com/rtomayko/rack-cache/issues/134
review plz: @alau @amatriain @krisdigital 
TODO:
make write return the read body and then return that, except for cases where that might be inefficient like Disk store
=> read from cache to deal with streamed bodies correctly

doc/configuration.markdown, lib/rack/cache/meta_store.rb, test/meta_store_test.rb
This contains #92 and #93, adds travis build configuration, adds missing docs for `use_native_ttl`, and cleans up the Rakefile.
@rtomayko if you're too busy I'm happy to help maintain this, just let me know.
=> Metastore TTL support

lib/rack/cache/response.rb, test/response_test.rb
PR https://github.com/rtomayko/rack-cache/pull/97 (which is merged) fixed an issue in which a date in the Expires header that did not conform to RFC 2616 caused the whole request to fail with an ArgumentError. 
However the fix should also be applied to the Date header. If Date has a value like "Sat, 2 Sep 2017 03:06:10 GMT" the request will fail because this date is not parseable according to the RFC2616 format (the month should have two digits, with a leading zero if necessary, so a correct value would be "Sat, 02 Sep 2017 03:06:10 GMT"). In the case of the Date header, if an ArgumentError is raised when parsing it, the current date should be returned, same as if the header is not present.
=> Return current date if the Date header is not parseable.

README.md
`config.middleware.use` inserts the middleware into a wrong place in the stack. As a result Rails' `ConditionalGet` turns all responses that are served from cache into 304s (blank pages for users).
=> Readme: fixed rails integration docs

.travis.yml, rack-cache.gemspec
travis fails because of a ruby 1.9 bug in minitest-line https://travis-ci.org/rtomayko/rack-cache/jobs/346354873
... time to drop 1.9 ? (old versions can still be used)
@rtomayko @amatriain @rmm5t
=> bump ruby requirement

CHANGES, lib/rack/cache/key.rb, rack-cache.gemspec, test/key_test.rb
Rack uses `to_s` in the `query_string` method, meaning `nil` will be converted to an empty string. However, when checking for the presence of the query string, Rack::Cache uses `.nil?`. As a result, Rack::Cache currently appends '?' to cache keys, even if the request does not include a query string.
Here is the relevant code in Rack: https://github.com/rack/rack/blob/master/lib/rack/request.rb#L136
=> Query string empty string

lib/rack/cache/meta_store.rb, test/meta_store_test.rb
Resolves issue https://github.com/rtomayko/rack-cache/issues/155 by warning once per class if purge isn't implemented.
A few notes:
1. I could not figure out a satisfactory way to truly warn on initialization in a backward compatible manner.
- The purge method itself has thrown `NotImplementedError` for a long time. It's really just the lookup method that needs resolution.
- There is no way to know at load time what implementation/configuration is actually going to be used. The only real way to do understand is catch the `NotImplementedError` in the `lookup`. Anything more seems to imply some other architectural changes that would require more than a patch level version update so I went with this for now.
2. I went with a simple `warn` call since that seems to be used elsewhere in the …
=> Warn once on X-Content-Digest entity store miss

.travis.yml, lib/rack/cache/context.rb, lib/rack/cache/entity_store.rb, lib/rack/cache/meta_store.rb, lib/rack/cache/storage.rb, test/context_test.rb, test/storage_test.rb, test/test_helper.rb
While implementing compression for `Redis::Rack::Cache` in
redis-store/redis-rack-cache#30, I noticed that it's not possible to
pass options down to the underlying store, resulting in a
less-than-ideal solution for users of the gem to configure whether they
want responses to be sent over the wire compressed to Redis and
decompressed on the way back. To resolve this, I propose that any
additional options not being used by `Rack::Cache` should be passed into
the underlying storage driver as a hash of options, although this is
backwards-compatible for drivers that don't need any additional options.
It would really help us out a lot if we had something like this in
`Rack::Cache` so custom options that only pertain to the underlying
store (such as connection pool or Redis cluster options) can …
=> Pass Options To Underlying Storage Driver

README.md, doc/configuration.markdown, lib/rack/cache/key.rb, test/key_test.rb
A proc for ignoring parts of query strings when generating a key. This is useful when you have parameters like `utm` or `trk` that don't affect the content on the page and are unique per-visitor or campaign. Parameters like these will be part of the key and cause a lot of churn.
Thought I'd open this as a PR to see if the maintainers were interested. Lemme know if otherwise, and I'll just monkey patch in my project!
=> Add a proc to allow ignoring parts of the query string in the key

lib/rack/cache/key.rb, test/key_test.rb
Currently when all Params are ignored with the proc given in Rack::Cache::Key.query_string_ignore, the resulting Cache-Key still contains the "?". This means, that the page cannot use the same cache as when using the same path without params.
=> remove query in key when all params are ignored

README.md
This PR changes two links in the README to use HTTPS.
=> README: Use https in hyperlinks

CHANGES, doc/configuration.markdown, lib/rack/cache/context.rb, lib/rack/cache/options.rb, rack-cache.gemspec, test/context_test.rb
Redoing #91 
> Rack::Cache includes an option to enable fault tolerant caching, so that stale cached results can be returned if the downstream service is unavailable. Just set :fault_tolerant => true in the options hash.
@grosser I agree that `fault_tolerant` can mean many things but can we keep this name? I tried to reflect other points in [your comment](https://github.com/rtomayko/rack-cache/pull/91#issuecomment-637916726).
@jfeltesse-mdsol @jcarres-mdsol
=> Add a fault_tolerant flag to fail-over to stale cache

lib/rack/cache/response.rb, test/context_test.rb
This must be a very rare case but we have experienced that when we changed a Cache-Control response header value 
of an endpoint (e.g. `public` -> `private, no-store`), the behavior of storing the response ([this line](https://github.com/rtomayko/rack-cache/blob/v1.12.0/lib/rack/cache/context.rb#L254)) didn't change:
https://github.com/rtomayko/rack-cache/blob/97819fb7cac8e80b5f2357400852cef49f088468/lib/rack/cache/context.rb#L254
Looks like this is happening.
When rack-cache is refreshing(updating) a cache, it makes a copy of an instance of Rack::Cache::Response class:
https://github.com/rtomayko/rack-cache/blob/97819fb7cac8e80b5f2357400852cef49f088468/lib/rack/cache/context.rb#L238
and updates the cached headers including Cache-Control.
However, the value of the Cache-Control header is …
=> Reset @cache_control in Response when duplicating its instance

lib/rack/cache/meta_store.rb, test/meta_store_test.rb
When we started receiving responses with a lowercased `vary` header, we observed cache miss and resulting in bloated cache entries.
When looking up the Vary header in a response, the headers are [looked up](https://github.com/rtomayko/rack-cache/blob/d4821f7c6063586a1e1ba7f706c107ce30a15d81/lib/rack/cache/response.rb#L251-L253) in a [case-insensitive hash implementation](https://github.com/rack/rack/blob/d15dd728440710cfc35ed155d66a98dc2c07ae42/lib/rack/utils.rb#L421-L425). 
However, when [persisting](https://github.com/rtomayko/rack-cache/blob/d4821f7c6063586a1e1ba7f706c107ce30a15d81/lib/rack/cache/meta_store.rb#L153), the headers are stored into a [normal (case-sensitive) hash](https://github.com/rack/rack/blob/d15dd728440710cfc35ed155d66a98dc2c07ae42/lib/rack/utils.rb#L458-L462).
The …
=> Fix case sensitivity of the Vary and Age headers
